# roles/microshift_config/tasks/main.yml

- name: Permanently disable SELinux
  ansible.posix.selinux:
    state: disabled
    policy: targeted   # Optional: Specify the policy if needed
  become: yes

- name: Disable SELinux
  command: setenforce 0
  ignore_errors: true
  become: yes

- name: Stop firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  become: yes

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes

- name: Ensure primary host is in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  with_items: "{{ groups['primary'] }}"
  when: inventory_hostname in groups['secondary']
  become: yes

- name: Ensure secondary hosts are in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  with_items: "{{ groups['secondary'] }}"
  when: inventory_hostname in groups['primary']
  become: yes
