---

- name: Copy the bootstrap kube configuration file to local
  copy:
    src: "/root/kubelet"
    dest: "/root/"
  become: yes

- name: Download and configure kubelet
  include_tasks: download_kubelet.yml

- name: Ensure /var/lib/microshift/resources/kubeadmin directory exists
  file:
    path: /var/lib/microshift/resources/kubeadmin
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Create hard link for kubeconfig
  command: ln -f "{{ kubelet_home }}/kubeconfig-{{ groups['primary'][0] }}" /var/lib/microshift/resources/kubeadmin/kubeconfig
  become: yes

- name: Remove old kubelet configuration file
  file:
    path: "{{ kubelet_home }}/kubeconfig"
    state: absent
  become: yes

- name: Enable and start crio service
  systemd:
    name: crio
    state: started
    enabled: yes
  become: yes

- name: Create kubelet systemd unit file
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started


